// Data from CSV
const studentsData = [
  { "name": "Nguyễn Thị Xuân Trang", "group": "Yêu Thương", "id": "001" },
  { "name": "Võ Nguyên Anh Minh", "group": "Yêu Thương", "id": "002" },
  { "name": "Lê Ngọc Linh Tuyền", "group": "Yêu Thương", "id": "003" },
  { "name": "Chu Duy Thức", "group": "Yêu Thương", "id": "004" },
  { "name": "Nguyễn Trung Tín", "group": "Yêu Thương", "id": "005" },
  { "name": "Trần Thành Đạt", "group": "Yêu Thương", "id": "006" },
  { "name": "Nguyễn Tấn Trung", "group": "Yêu Thương", "id": "007" },
  { "name": "Huỳnh Ngọc Ánh Tuyết", "group": "Yêu Thương", "id": "008" },
  { "name": "Trần Hoàng Quân", "group": "Yêu Thương", "id": "009" },
  { "name": "Nguyễn Thiên Thi", "group": "Yêu Thương", "id": "010" },
  { "name": "Nguyễn Cao Kỳ Duyên", "group": "Yêu Thương", "id": "011" },
  { "name": "Trần Tấn Phúc", "group": "Yêu Thương", "id": "012" },
  { "name": "Nguyễn Thị Minh Trang", "group": "Yêu Thương", "id": "013" },
  { "name": "Đặng Thị Trúc Ngân", "group": "Yêu Thương", "id": "014" },
  { "name": "Trần Thị Thiên Hằng", "group": "Yêu Thương", "id": "015" },
  { "name": "Dương Huyền Ngự", "group": "Yêu Thương", "id": "016" },
  { "name": "Trần Lâm Phương Nhi", "group": "Yêu Thương", "id": "017" },
  { "name": "Võ Chí Đức", "group": "Yêu Thương", "id": "018" },
  { "name": "Nguyễn Thị Như Linh", "group": "Yêu Thương", "id": "019" },
  { "name": "Nguyễn Văn Tú Ân", "group": "Yêu Thương", "id": "020" },
  { "name": "Phan Vĩnh Thiện Khôi", "group": "Yêu Thương", "id": "021" },
  { "name": "Trần Thiên Ái", "group": "Yêu Thương", "id": "022" },
  { "name": "Hồ Thị Thùy Dương", "group": "Vui Mừng", "id": "023" },
  { "name": "Bùi Thị Thanh Nga", "group": "Vui Mừng", "id": "024" },
  { "name": "Nguyễn Thị Thùy Linh", "group": "Vui Mừng", "id": "025" },
  { "name": "Trương Kim Thanh", "group": "Vui Mừng", "id": "026" },
  { "name": "Lâm Hồ Thúy Nhơn", "group": "Vui Mừng", "id": "027" },
  { "name": "Diệp Khương Anh", "group": "Vui Mừng", "id": "028" },
  { "name": "Nguyễn Thị Kim Ngân", "group": "Vui Mừng", "id": "029" },
  { "name": "Lê Quỳnh Nhi", "group": "Vui Mừng", "id": "030" },
  { "name": "Lê Khả Vy", "group": "Vui Mừng", "id": "031" },
  { "name": "Phan Thị Quỳnh Giang", "group": "Vui Mừng", "id": "032" },
  { "name": "Nguyễn Nam Trân", "group": "Vui Mừng", "id": "033" },
  { "name": "Trần Hán Tài", "group": "Vui Mừng", "id": "034" },
  { "name": "Galet Ênuôl", "group": "Vui Mừng", "id": "035" },
  { "name": "Trần Ngọc Anh Thư", "group": "Vui Mừng", "id": "036" },
  { "name": "Trương Đình Kỳ", "group": "Vui Mừng", "id": "037" },
  { "name": "Nguyễn Ngọc Nhật Mai", "group": "Vui Mừng", "id": "038" },
  { "name": "Ksor Sắc", "group": "Vui Mừng", "id": "039" },
  { "name": "Nguyễn Thanh Hoà", "group": "Vui Mừng", "id": "040" },
  { "name": "Phan Giảng Bình", "group": "Vui Mừng", "id": "041" },
  { "name": "Huỳnh Nguyễn Bửu Ngọc", "group": "Vui Mừng", "id": "042" },
  { "name": "Tô Đông Phong", "group": "Vui Mừng", "id": "043" },
  { "name": "Lê Trần Nhạc Khuê", "group": "Vui Mừng", "id": "044" },
  { "name": "Lê Phú Thịnh", "group": "Vui Mừng", "id": "045" },
  { "name": "Nguyễn Thục Thiên Ân", "group": "Vui Mừng", "id": "046" },
  { "name": "Nguyễn Minh Tiến", "group": "Vui Mừng", "id": "047" },
  { "name": "Điểu Thị Sách", "group": "Vui Mừng", "id": "048" },
  { "name": "Đặng Tiểu Hạo", "group": "Vui Mừng", "id": "049" },
  { "name": "Đoàn Minh Thạch", "group": "Vui Mừng", "id": "050" },
  { "name": "Nguyễn Thị Thuận Phục", "group": "Vui Mừng", "id": "051" },
  { "name": "Phan Nguyễn Trâm Anh", "group": "Vui Mừng", "id": "052" },
  { "name": "Thị Oanh", "group": "Vui Mừng", "id": "053" },
  { "name": "Trương Đặng Linh Đăng", "group": "Bình An", "id": "054" },
  { "name": "Huỳnh Xuân Hiền", "group": "Bình An", "id": "055" },
  { "name": "Trần Phan Thu Ngân", "group": "Bình An", "id": "056" },
  { "name": "Nguyễn Đăng Huy", "group": "Bình An", "id": "057" },
  { "name": "Trần Thị Mỹ Lộc", "group": "Bình An", "id": "058" },
  { "name": "Nguyễn Thiện Nhân", "group": "Bình An", "id": "059" },
  { "name": "Đặng Hoàng Ý Nhi", "group": "Bình An", "id": "060" },
  { "name": "Nguyễn Đình Cao Sang", "group": "Bình An", "id": "061" },
  { "name": "Phạm Linh Đan", "group": "Bình An", "id": "062" },
  { "name": "Lê Minh Khoa", "group": "Bình An", "id": "063" },
  { "name": "Phạm Nguyễn Nguyên Khôi", "group": "Bình An", "id": "064" },
  { "name": "Ông Thị Thục Hồng", "group": "Bình An", "id": "065" },
  { "name": "H Xuân Êban", "group": "Bình An", "id": "066" },
  { "name": "Đoàn Đại Ngữ", "group": "Bình An", "id": "067" },
  { "name": "Trần Công Bình", "group": "Bình An", "id": "068" },
  { "name": "Tô Phương Thảo", "group": "Bình An", "id": "069" },
  { "name": "Nguyễn Trần Thy Thy", "group": "Bình An", "id": "070" },
  { "name": "Dương Phạm Ngọc Châu", "group": "Bình An", "id": "071" },
  { "name": "Lê Minh Đức", "group": "Bình An", "id": "072" },
  { "name": "Nguyễn Hà Nam Trân", "group": "Bình An", "id": "073" },
  { "name": "Nguyễn Trần Khánh Linh", "group": "Bình An", "id": "074" },
  { "name": "Đặng Hồ Nhật Khánh", "group": "Bình An", "id": "075" },
  { "name": "Huỳnh Vĩnh Hằng", "group": "Bình An", "id": "076" },
  { "name": "Lâm Mai Trang", "group": "Nhịn Nhục", "id": "077" },
  { "name": "Trần Lê Minh Tướng", "group": "Nhịn Nhục", "id": "078" },
  { "name": "Đỗ Ngọc Hân", "group": "Nhịn Nhục", "id": "079" },
  { "name": "Nguyễn Hoàng Anh Thư", "group": "Nhịn Nhục", "id": "080" },
  { "name": "Đặng Hoàng Anh", "group": "Nhịn Nhục", "id": "081" },
  { "name": "Cao Nguyễn Anh Thư", "group": "Nhịn Nhục", "id": "082" },
  { "name": "Lê Vĩnh Toàn", "group": "Nhịn Nhục", "id": "083" },
  { "name": "Âu Gia Thịnh", "group": "Nhịn Nhục", "id": "084" },
  { "name": "Phạm Nguyễn Hoàng Tân", "group": "Nhịn Nhục", "id": "085" },
  { "name": "Long Minh Tâm", "group": "Nhịn Nhục", "id": "086" },
  { "name": "Tạ Lâm Tuyết Nhung", "group": "Nhịn Nhục", "id": "087" },
  { "name": "Phan Nguyễn Vân Anh", "group": "Nhịn Nhục", "id": "088" },
  { "name": "Nguyễn Hoàng Vân Anh", "group": "Nhịn Nhục", "id": "089" },
  { "name": "Phạm Duy Thành", "group": "Nhịn Nhục", "id": "090" },
  { "name": "Trần Thị Nhật Lệ", "group": "Nhịn Nhục", "id": "091" },
  { "name": "Lê Huỳnh Trường Hải", "group": "Nhịn Nhục", "id": "092" },
  { "name": "Trịnh Thành Danh", "group": "Nhịn Nhục", "id": "093" },
  { "name": "Đặng Thị Xuân Hoà", "group": "Nhịn Nhục", "id": "094" },
  { "name": "Trương Minh Triết", "group": "Nhịn Nhục", "id": "095" },
  { "name": "Lê Văn Tài", "group": "Nhịn Nhục", "id": "096" },
  { "name": "Lê Ngọc Bảo Trân", "group": "Nhịn Nhục", "id": "097" },
  { "name": "Nguyễn Quang Hảo", "group": "Nhịn Nhục", "id": "098" },
  { "name": "Trần Thuý Nga", "group": "Nhịn Nhục", "id": "099" },
  { "name": "Đào Huyền Trân", "group": "Nhịn Nhục", "id": "100" },
  { "name": "Lê Nhật Quang", "group": "Nhịn Nhục", "id": "101" },
  { "name": "Trần Ngọc Nhã Thy", "group": "Nhịn Nhục", "id": "102" },
  { "name": "Trần Bích Duyên", "group": "Nhịn Nhục", "id": "103" },
  { "name": "Lương Hoàng An Nhật", "group": "Nhịn Nhục", "id": "104" },
  { "name": "Nguyễn Thanh Vân", "group": "Nhân Từ", "id": "105" },
  { "name": "Giang Hoàng Cao Quí", "group": "Nhân Từ", "id": "106" },
  { "name": "H Joy Kbuôr", "group": "Nhân Từ", "id": "107" },
  { "name": "Trần Thanh Phong", "group": "Nhân Từ", "id": "108" },
  { "name": "Ôn Thành Long", "group": "Nhân Từ", "id": "109" },
  { "name": "Lê Hải Yến", "group": "Nhân Từ", "id": "110" },
  { "name": "Đỗ Cẩm Nguyên", "group": "Nhân Từ", "id": "111" },
  { "name": "H Ôni Niê Siêng", "group": "Nhân Từ", "id": "112" },
  { "name": "Nguyễn Thị Châu Quỳnh", "group": "Nhân Từ", "id": "113" },
  { "name": "Nguyễn Tấn Hậu", "group": "Nhân Từ", "id": "114" },
  { "name": "Dương Ngọc Quí", "group": "Nhân Từ", "id": "115" },
  { "name": "Nguyễn Trương Hoàng Hân", "group": "Nhân Từ", "id": "116" },
  { "name": "Lê Thị Ngọc Hân", "group": "Nhân Từ", "id": "117" },
  { "name": "Nguyễn Thiên Ân", "group": "Nhân Từ", "id": "118" },
  { "name": "Lưu Mỹ Nguyên", "group": "Nhân Từ", "id": "119" },
  { "name": "Lê Hoàng Khang", "group": "Nhân Từ", "id": "120" },
  { "name": "Nguyễn Song Thiên Phúc", "group": "Nhân Từ", "id": "121" },
  { "name": "Đinh Trí Thiên Bảo", "group": "Nhân Từ", "id": "122" },
  { "name": "Lương Tường Vy", "group": "Nhân Từ", "id": "123" },
  { "name": "Lương Đức Minh", "group": "Hiền Lành", "id": "124" },
  { "name": "Lê Ngọc Ái Linh", "group": "Hiền Lành", "id": "125" },
  { "name": "Nguyễn Sĩ Nhân", "group": "Hiền Lành", "id": "126" },
  { "name": "Nguyễn Hồng Chương", "group": "Hiền Lành", "id": "127" },
  { "name": "Phạm Bá Nam", "group": "Hiền Lành", "id": "128" },
  { "name": "Nguyễn Ngọc Gia Hân", "group": "Hiền Lành", "id": "129" },
  { "name": "Đoàn Lê Yến Phương", "group": "Hiền Lành", "id": "130" },
  { "name": "Ngô Phụng Tiên", "group": "Hiền Lành", "id": "131" },
  { "name": "Vương Vĩnh Thái", "group": "Hiền Lành", "id": "132" },
  { "name": "Nguyễn Thị Phương Thanh", "group": "Hiền Lành", "id": "133" },
  { "name": "Võ Nhật Duy", "group": "Hiền Lành", "id": "134" },
  { "name": "Phạm Phát Đạt", "group": "Hiền Lành", "id": "135" },
  { "name": "Phan An Thịnh", "group": "Hiền Lành", "id": "136" },
  { "name": "Nguyễn Thị Hoàng Diệu", "group": "Hiền Lành", "id": "137" },
  { "name": "Nguyễn Ngô Hoàng Huy", "group": "Hiền Lành", "id": "138" },
  { "name": "Trần Lê Phương Nhã", "group": "Hiền Lành", "id": "139" },
  { "name": "Nguyễn Thị Kim Ngân", "group": "Hiền Lành", "id": "140" },
  { "name": "Nguyễn Hoàng An Khang", "group": "Hiền Lành", "id": "141" },
  { "name": "Nguyễn Hằng Hương Giang", "group": "Hiền Lành", "id": "142" },
  { "name": "Trương Ngọc Linh", "group": "Trung Tín", "id": "143" },
  { "name": "Nguyễn Ngọc Bảo Nghi", "group": "Trung Tín", "id": "144" },
  { "name": "Nguyễn Minh Việt", "group": "Trung Tín", "id": "145" },
  { "name": "H Nhan Ktla", "group": "Trung Tín", "id": "146" },
  { "name": "Phạm Đoàn Tố Trân", "group": "Trung Tín", "id": "147" },
  { "name": "Phạm Lê Bảo Ngọc", "group": "Trung Tín", "id": "148" },
  { "name": "Nguyễn Thanh Vân", "group": "Trung Tín", "id": "149" },
  { "name": "Huỳnh Khương Ninh", "group": "Trung Tín", "id": "150" },
  { "name": "Lê Bảo Thiên Ân", "group": "Trung Tín", "id": "151" },
  { "name": "Hà Phúc Thiên", "group": "Trung Tín", "id": "152" },
  { "name": "Phạm Duy", "group": "Trung Tín", "id": "153" },
  { "name": "Trương Ngọc Mỹ", "group": "Trung Tín", "id": "154" },
  { "name": "Võ Tiến Cường", "group": "Trung Tín", "id": "155" },
  { "name": "Trịnh Ngọc Thiên Phú", "group": "Trung Tín", "id": "156" },
  { "name": "Nguyễn Triệu Ân", "group": "Trung Tín", "id": "157" },
  { "name": "Đoàn Gia Kiệt", "group": "Trung Tín", "id": "158" },
  { "name": "Trương Quỳnh My", "group": "Trung Tín", "id": "159" },
  { "name": "Trần Quang", "group": "Trung Tín", "id": "160" },
  { "name": "Nguyễn Phạm Phương Thảo", "group": "Trung Tín", "id": "161" },
  { "name": "Võ Văn Đầy", "group": "Mềm Mại", "id": "162" },
  { "name": "Nguyễn Phạm Thanh Phương", "group": "Mềm Mại", "id": "163" },
  { "name": "Ngô Tấn Phát", "group": "Mềm Mại", "id": "164" },
  { "name": "Nguyễn Cao Đại", "group": "Mềm Mại", "id": "165" },
  { "name": "Lê Thị Thuỳ Dương", "group": "Mềm Mại", "id": "166" },
  { "name": "Huỳnh Thị Yến Linh", "group": "Mềm Mại", "id": "167" },
  { "name": "Nguyễn Hoàng Anh", "group": "Mềm Mại", "id": "168" },
  { "name": "Nguyễn Thị Hồng Trâm", "group": "Mềm Mại", "id": "169" },
  { "name": "Võ Thị Mỹ Duyên", "group": "Mềm Mại", "id": "170" },
  { "name": "Trần Hữu Phúc", "group": "Mềm Mại", "id": "171" },
  { "name": "Huỳnh Ngọc Tâm Anh", "group": "Mềm Mại", "id": "172" },
  { "name": "Trương Vĩnh Phúc", "group": "Mềm Mại", "id": "173" },
  { "name": "Trần Thị Ngọc Thảo", "group": "Mềm Mại", "id": "174" },
  { "name": "Đặng Gia Huy", "group": "Mềm Mại", "id": "175" },
  { "name": "Trương Nguyễn Thiên Ý", "group": "Mềm Mại", "id": "176" },
  { "name": "Nguyễn Thanh Thảo Vi", "group": "Mềm Mại", "id": "177" },
  { "name": "Trương Kim Nguyệt", "group": "Mềm Mại", "id": "178" },
  { "name": "Nguyễn Tuấn Vũ", "group": "Mềm Mại", "id": "179" },
  { "name": "Huỳnh Anh Thái Ngọc", "group": "Mềm Mại", "id": "180" },
  { "name": "Văn Trung", "group": "Mềm Mại", "id": "181" },
  { "name": "Bùi Trương Huỳnh Duyên", "group": "Mềm Mại", "id": "182" },
  { "name": "Trần Thị Tú Uyên", "group": "Mềm Mại", "id": "183" },
  { "name": "Phạm Hoàng Lên", "group": "Mềm Mại", "id": "184" },
  { "name": "Hoel Nie", "group": "Mềm Mại", "id": "185" }
];

// // Admin key (in real app, this should be more secure)
// const ADMIN_KEY = "jkl";

// Group students by group name
const groupedStudents = studentsData.reduce((acc, student) => {
  if (!acc[student.group]) {
    acc[student.group] = [];
  }
  acc[student.group].push(student);
  return acc;
}, {});